--
-- PostgreSQL database dump
--

-- Dumped from database version 15.5 (Ubuntu 15.5-0ubuntu0.23.10.1)
-- Dumped by pg_dump version 15.5 (Ubuntu 15.5-0ubuntu0.23.10.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answer (
    id integer NOT NULL,
    possible_answer_id bigint NOT NULL,
    text_value character varying,
    app_user_id bigint NOT NULL
);


ALTER TABLE public.answer OWNER TO postgres;

--
-- Name: answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id integer NOT NULL,
    firstname character varying NOT NULL,
    lastname character varying NOT NULL,
    email character varying NOT NULL,
    job_title character varying NOT NULL,
    profile_picture_name character varying,
    dict_occupation_id bigint NOT NULL,
    dict_target_occupation_id bigint NOT NULL,
    dict_interest_id bigint NOT NULL,
    selected_conference_id bigint,
    password character varying,
    reset_code character varying,
    reset_code_expire_date timestamp without time zone
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_room (
    id integer NOT NULL,
    conference_id bigint,
    round_id bigint,
    panel_id bigint,
    is_home_chat boolean NOT NULL
);


ALTER TABLE public.chat_room OWNER TO postgres;

--
-- Name: chat_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_room_member; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_room_member (
    chat_room_id bigint NOT NULL,
    app_user_id bigint NOT NULL,
    last_read_message_id bigint
);


ALTER TABLE public.chat_room_member OWNER TO postgres;

--
-- Name: conference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conference (
    id integer NOT NULL,
    pin character varying,
    agenda_name character varying NOT NULL,
    is_participant_list_available boolean NOT NULL,
    start_date timestamp without time zone NOT NULL,
    stop_date timestamp without time zone NOT NULL
);


ALTER TABLE public.conference OWNER TO postgres;

--
-- Name: conference_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: dictionary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dictionary (
    id integer NOT NULL,
    name character varying,
    dictionary_type character varying
);


ALTER TABLE public.dictionary OWNER TO postgres;

--
-- Name: dictionary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dictionary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dictionary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dictionary_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.dictionary_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.dictionary_seq OWNER TO postgres;

--
-- Name: email_scheduler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_scheduler (
    id integer NOT NULL,
    receiver_name character varying NOT NULL,
    receiver_email character varying NOT NULL,
    type character varying NOT NULL,
    message character varying,
    tries numeric NOT NULL
);


ALTER TABLE public.email_scheduler OWNER TO postgres;

--
-- Name: email_scheduler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.email_scheduler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_scheduler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message (
    id integer NOT NULL,
    chat_room_id bigint,
    date timestamp without time zone,
    app_user_id bigint,
    type character varying,
    text character varying,
    order_in_chat numeric NOT NULL
);


ALTER TABLE public.message OWNER TO postgres;

--
-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: panel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.panel (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    round_id bigint NOT NULL,
    start_date timestamp without time zone NOT NULL,
    stop_date timestamp without time zone NOT NULL,
    start_notification_sent boolean NOT NULL,
    stop_notification_sent boolean NOT NULL
);


ALTER TABLE public.panel OWNER TO postgres;

--
-- Name: panel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.panel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.panel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: possible_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.possible_answer (
    id integer NOT NULL,
    caption character varying NOT NULL,
    question_id bigint NOT NULL,
    "order" bigint
);


ALTER TABLE public.possible_answer OWNER TO postgres;

--
-- Name: possible_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.possible_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.possible_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question (
    id integer NOT NULL,
    question character varying NOT NULL,
    question_type character varying NOT NULL,
    survey_id bigint NOT NULL,
    "order" bigint
);


ALTER TABLE public.question OWNER TO postgres;

--
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: round; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.round (
    id integer NOT NULL,
    name character varying NOT NULL,
    conference_id bigint,
    img_path character varying
);


ALTER TABLE public.round OWNER TO postgres;

--
-- Name: round_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.round ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session (
    id integer NOT NULL,
    app_user_id bigint NOT NULL,
    session_key character varying NOT NULL,
    expiration_date timestamp without time zone
);


ALTER TABLE public.session OWNER TO postgres;

--
-- Name: session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey (
    id integer NOT NULL,
    name character varying NOT NULL,
    round_id bigint,
    start_date timestamp without time zone,
    stop_date timestamp without time zone,
    start_notification_sent boolean NOT NULL,
    stop_notification_sent boolean NOT NULL
);


ALTER TABLE public.survey OWNER TO postgres;

--
-- Name: survey_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.survey ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: answer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.answer (id, possible_answer_id, text_value, app_user_id) FROM stdin;
\.


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user (id, firstname, lastname, email, job_title, profile_picture_name, dict_occupation_id, dict_target_occupation_id, dict_interest_id, selected_conference_id, password, reset_code, reset_code_expire_date) FROM stdin;
19	Rares	Hurghis	Rares.hurghis@engie.com	Strategy Project Manager	36fcd056-080e-4b3a-b8c3-496070126932	17	15	33	\N	f41dbf83a5e2b3e9e3e5843bc6ecfc01	\N	\N
2	Evelin	Szoke	evelin.szoke@whitepaperconsulting.hu	Project Manager	\N	1	7	41	1	96480a2fb4da2fadeb194a8555a2f660	\N	\N
3	Ekomobong 	Alfred	ekomobong@nigeriangasassociation.orgng	Lawyer 	94f4fef3-4934-4212-8fee-7f5fcb4f0d80	6	17	32	1	98d9a4c28dc652ce06cac60157e60396	\N	\N
4	Leszek	Ostek	ostek.leszek@gmail.com	Programmer	\N	2	2	25	1	a5d57afca1d11ee17a6caddaeea5e704	\N	\N
5	Istvan	Zentai	istvan.zentai@spacebuzzfoundation.hu	Chair of the Board of Trustees	300fef0f-c342-4a60-8b6a-433bee763965	14	23	40	1	b73abfaec2c86c0e5e31b7324d98a3be	\N	\N
6	Nora	Dr Kovacs	nora.kovacs@bakermckenzie.com	Attorney	\N	6	7	39	1	f0a2afaabaf42bd076d86abb174572ef	\N	\N
7	Zsofia	Biro	dr.biro.zsofia@gmail.com	Research Fellow	459ac03e-8bda-4867-86e1-732d6f7b37bf	4	7	41	1	62e25a9346ac4713ddb10e20b5edbe70	\N	\N
8	Tibor	Szatmari	drszatmaritibor@gmail.com	Senior International Advisor MENA	\N	7	24	40	1	936b70137a7857400c168f6d0f84e651	\N	\N
9	Nora Zsuzsanna	Dr Kovacs	Nora.Kovacs@bakermckenzie.com	Attorney at Baker McKenzie	607a3bc2-3abc-409f-8450-0a9585835481	6	7	39	1	d7f58bdc420fac6664bf14f8e9ae9a42	\N	\N
10	Hadeer	Hassan	hm.geophysicist@gmail.com	Researcher 	\N	4	4	32	1	d147961e52ea497eb2c2ee3185854a40	\N	\N
11	Kitti	Pasztor	pasztor.kitti.333@gmail.com	Nonprofit	191bff1f-2369-4424-954d-6496e4291f4a	4	11	37	1	ace6fa73a65da5d70a7b6b23ee5a59ca	\N	\N
12	Toma	Milic	michal230915@gmail.com	sad	\N	1	1	26	1	2281159749ec33473ddb1712a73305eb	\N	\N
18	Dominik	Istrate	d.istrate@areterapa.com	Senior CEE Analyst	d492ea57-bd97-4ec8-b608-613446e0a1c5	4	22	26	1	8833fd4f981aed87c6cd5e16ca9863e2	\N	\N
15	Vass	Imre	iva@ournewenergy.com	Partner	679d654e-b70d-401a-ae3d-98d1e71dd55e	23	19	30	1	6c73f173fb7655047a82d802434ae7d6	\N	\N
13	Ambrus	Galantai	ambrus.galantai@stxgroup.com	Regional Lead CEE	9d7995a7-e448-4f00-8d95-742920bcf886	23	12	41	1	d609a0a30571dfdc7605564b34f7f3c9	\N	\N
14	Ramin	MAMMADOV	ramin.mammadov@gmail.com	Member of Parliament	\N	11	24	41	1	126b58a9667cb46089c147f6a8aa5cb1	\N	\N
16	Arijeta	Pajaziti Qerimi	apajaziti@gmail.com	SCADA EMS engineer specialist	\N	5	5	34	1	b99017b1878e4513c72a18449f35eed2	\N	\N
1	Filip	Derewenda	filip.derewenda@gmail.com	Journalist	4a294151-ae16-4f26-b820-d23def222afd	1	11	25	1	d58c14b8b20307d773fede189352f937	\N	\N
17	Krisztina	Dr Gyepes	gyepes.krisztina@gyepespartners.com	Partner	\N	5	5	26	1	447da28d0907d46667fb2671550338ff	\N	\N
\.


--
-- Data for Name: chat_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_room (id, conference_id, round_id, panel_id, is_home_chat) FROM stdin;
1	1	\N	\N	f
2	1	\N	\N	t
3	1	\N	\N	f
4	1	\N	\N	f
5	1	\N	\N	f
6	1	\N	\N	t
7	1	\N	\N	f
8	1	\N	\N	f
9	1	\N	\N	f
10	1	\N	\N	f
11	1	\N	\N	f
12	1	\N	\N	f
13	1	\N	\N	f
14	1	\N	\N	t
15	1	\N	\N	f
16	1	\N	\N	f
17	1	\N	\N	f
18	1	\N	\N	t
100	\N	\N	1	f
19	1	\N	\N	f
20	1	\N	\N	f
21	1	\N	\N	f
22	1	\N	\N	t
23	1	\N	\N	f
24	1	\N	\N	f
25	1	\N	\N	f
26	1	\N	\N	f
27	1	\N	\N	f
28	1	\N	\N	t
29	1	\N	\N	f
30	1	\N	\N	f
31	1	\N	\N	f
32	1	\N	\N	f
33	1	\N	\N	f
\.


--
-- Data for Name: chat_room_member; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_room_member (chat_room_id, app_user_id, last_read_message_id) FROM stdin;
1	1	\N
2	1	\N
100	2	\N
2	2	\N
3	2	\N
100	3	\N
2	3	\N
4	3	\N
5	4	\N
6	4	\N
7	1	32
2	7	\N
10	7	\N
11	4	\N
11	3	\N
100	5	\N
6	5	\N
8	5	\N
100	8	\N
6	8	\N
12	8	\N
100	9	\N
13	9	\N
14	9	\N
100	10	\N
14	10	\N
15	10	\N
14	11	\N
16	11	\N
17	12	\N
18	12	\N
100	13	\N
18	13	\N
19	13	\N
100	14	\N
18	14	\N
20	14	\N
100	16	\N
21	16	\N
22	16	\N
100	1	33
100	4	33
23	11	\N
23	1	\N
24	14	\N
24	1	34
100	17	\N
22	17	\N
25	17	\N
100	7	33
22	18	\N
26	18	\N
100	6	\N
2	6	\N
9	6	\N
29	3	\N
30	14	\N
30	18	41
27	18	44
29	18	45
27	1	44
31	1	\N
31	16	\N
100	15	\N
28	15	\N
32	15	\N
100	11	33
33	13	\N
100	18	33
33	18	46
100	12	33
7	4	48
\.


--
-- Data for Name: conference; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.conference (id, pin, agenda_name, is_participant_list_available, start_date, stop_date) FROM stdin;
1	123123	Budapest Climate Summit	t	2023-11-08 19:03:00.541	2023-11-08 19:03:00.541
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
create-conference-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.773219	1	EXECUTED	8:65b245c7405a322b8dbd618ad5b38079	createTable tableName=conference		\N	4.21.1	\N	\N	1332916402
create-dictionary-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.794578	2	EXECUTED	8:2253283e54badb3c54a9b94da44dc73a	createTable tableName=dictionary		\N	4.21.1	\N	\N	1332916402
create-app-user-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.834344	3	EXECUTED	8:71482ec4427384866df8b5de4c8755e4	createTable tableName=app_user; addForeignKeyConstraint baseTableName=app_user, constraintName=fk_dict_occupation_app_user, referencedTableName=dictionary; addForeignKeyConstraint baseTableName=app_user, constraintName=fk_target_occupation_app_use...		\N	4.21.1	\N	\N	1332916402
create-session-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.864122	4	EXECUTED	8:6f99b4d5046993a71f9d870e5ea52f5c	createTable tableName=session; addUniqueConstraint constraintName=unique_app_user_id, tableName=session; addForeignKeyConstraint baseTableName=session, constraintName=fk_session_app_user, referencedTableName=app_user		\N	4.21.1	\N	\N	1332916402
create-round-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.88447	5	EXECUTED	8:c6a9ab90450e1eefdcfe2fd83a1edd1c	createTable tableName=round; addForeignKeyConstraint baseTableName=round, constraintName=fk_round_conference, referencedTableName=conference		\N	4.21.1	\N	\N	1332916402
create-survey-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.901736	6	EXECUTED	8:256938ddc5252bdb66051ffcda8530fe	createTable tableName=survey; addForeignKeyConstraint baseTableName=survey, constraintName=fk_survey_round, referencedTableName=round		\N	4.21.1	\N	\N	1332916402
create-question-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.93338	7	EXECUTED	8:b1527759d8a6b01d761e168ed021bfce	createTable tableName=question; addForeignKeyConstraint baseTableName=question, constraintName=fk_question_survey, referencedTableName=survey		\N	4.21.1	\N	\N	1332916402
create-possible-answer-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.951804	8	EXECUTED	8:723553bed3ade09b64c4c79b3493159f	createTable tableName=possible_answer; addForeignKeyConstraint baseTableName=possible_answer, constraintName=fk_possible_answer_question, referencedTableName=question		\N	4.21.1	\N	\N	1332916402
create-answer-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.973127	9	EXECUTED	8:6bc88e24a224f87c3e9215f717c5d093	createTable tableName=answer; addForeignKeyConstraint baseTableName=answer, constraintName=fk_answer_possible_answer, referencedTableName=possible_answer; addForeignKeyConstraint baseTableName=answer, constraintName=fk_answer_app_user, referencedT...		\N	4.21.1	\N	\N	1332916402
create-panel-table	lostek	db/changelogs/create-database.xml	2023-11-30 08:28:36.992404	10	EXECUTED	8:4ccba2465b6786f1d764c953d18e7ff3	createTable tableName=panel; addForeignKeyConstraint baseTableName=panel, constraintName=fk_panel_round, referencedTableName=round		\N	4.21.1	\N	\N	1332916402
create-chat-room-table	mkalina	db/changelogs/create-database.xml	2023-11-30 08:28:37.013226	11	EXECUTED	8:b7c8b2873b7e0d6627e84016595b6dde	createTable tableName=chat_room; addForeignKeyConstraint baseTableName=chat_room, constraintName=fk_chat_room_conference, referencedTableName=conference; addForeignKeyConstraint baseTableName=chat_room, constraintName=fk_chat_room_round, reference...		\N	4.21.1	\N	\N	1332916402
create-message-table	mkalina	db/changelogs/create-database.xml	2023-11-30 08:28:37.036607	12	EXECUTED	8:8a586cd27444e6baedf1c1016cfe97bc	createTable tableName=message; addForeignKeyConstraint baseTableName=message, constraintName=fk_message_chat, referencedTableName=chat_room; addForeignKeyConstraint baseTableName=message, constraintName=fk_message_sender, referencedTableName=app_user		\N	4.21.1	\N	\N	1332916402
create-chat-room-member-table	mkalina	db/changelogs/create-database.xml	2023-11-30 08:28:37.073895	13	EXECUTED	8:25183f94723af1f73e10e7ccdf295849	createTable tableName=chat_room_member; addUniqueConstraint constraintName=unique_chat_room_app_user, tableName=chat_room_member; addForeignKeyConstraint baseTableName=chat_room_member, constraintName=fk_chat_room_member_chat_room, referencedTable...		\N	4.21.1	\N	\N	1332916402
create-email_scheduler-table	mkalina	db/changelogs/create-database.xml	2023-11-30 08:28:37.095882	14	EXECUTED	8:5c18794d73aeb151bee3ac08f3895317	createTable tableName=email_scheduler		\N	4.21.1	\N	\N	1332916402
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: dictionary; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dictionary (id, name, dictionary_type) FROM stdin;
1	Media & Communications	OCCUPATION
2	Information Technology - IT	OCCUPATION
3	Finance & Banking	OCCUPATION
4	Research and Academia	OCCUPATION
5	Engineering	OCCUPATION
6	Legal	OCCUPATION
7	Business & Management	OCCUPATION
8	Sales & Marketing	OCCUPATION
9	Science & Research	OCCUPATION
10	Agriculture & Farming	OCCUPATION
11	Government & Public Administration	OCCUPATION
12	Manufacturing & Production	OCCUPATION
13	Transportation & Logistics	OCCUPATION
14	Social Services & Nonprofits	OCCUPATION
15	Traditional Energy Sector – Oil & Gas 	OCCUPATION
16	Traditional Energy Sector – LNG 	OCCUPATION
17	Traditional Energy Sector - Other 	OCCUPATION
18	Clean Energy Sector – Wind	OCCUPATION
19	Clean Energy Sector – Solar 	OCCUPATION
20	Clean Energy Sector – Geothermal 	OCCUPATION
21	Clean Energy Sector – Green Hydrogen 	OCCUPATION
22	Clean Energy Sector – Nuclear	OCCUPATION
23	Clean Energy Sector – Other	OCCUPATION
24	Climate Activism and Environmental Protection	OCCUPATION
25	Electromobility	INTEREST
26	Solar Energy	INTEREST
27	Wind Energy	INTEREST
28	Hydro Energy	INTEREST
29	Nuclear Energy	INTEREST
30	Battery Technology	INTEREST
31	Geothermal Energy	INTEREST
32	Oil/Gas/LNG Industries	INTEREST
33	Hydrogen	INTEREST
34	Electricity Sector	INTEREST
35	Bioenergy	INTEREST
36	Coal	INTEREST
37	EU Energy and Climate Policies	INTEREST
38	Energy Efficiency	INTEREST
39	Sustainable Finance	INTEREST
40	Circular Economy	INTEREST
41	Green Transition	INTEREST
\.


--
-- Data for Name: email_scheduler; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.email_scheduler (id, receiver_name, receiver_email, type, message, tries) FROM stdin;
\.


--
-- Data for Name: message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.message (id, chat_room_id, date, app_user_id, type, text, order_in_chat) FROM stdin;
1	7	2023-11-30 10:55:13.35009	4	MESSAGE	Hej	0
2	7	2023-11-30 10:55:19.847298	4	MESSAGE	Co tam	1
3	7	2023-11-30 10:57:22.218718	1	MESSAGE	gowno	2
4	7	2023-11-30 10:58:17.887174	4	MESSAGE	😂	3
5	7	2023-11-30 10:58:41.582067	4	MESSAGE	Mnie dalo do innej grupy	4
6	7	2023-11-30 10:58:45.507266	4	MESSAGE	Wiec gitowa	5
7	7	2023-11-30 11:21:58.638331	1	MESSAGE	ej to grupy sa trzy osobowe?	6
8	7	2023-11-30 11:22:15.485298	4	MESSAGE	Maks 5 os	7
9	7	2023-11-30 11:22:27.079466	1	MESSAGE	ej a jestes w grupie z Istvan Zentai?	8
10	7	2023-11-30 11:22:29.008714	1	MESSAGE	XD	9
11	7	2023-11-30 11:22:39.702322	1	MESSAGE	czy na razie z nikim?	10
12	7	2023-11-30 11:22:55.126672	4	MESSAGE	Z tym typem mnie dobrało	11
13	7	2023-11-30 11:23:10.626297	4	MESSAGE	Nie mam z nim wspolnych rzeczy ale bylem sam	12
14	7	2023-11-30 11:23:24.605693	4	MESSAGE	Wiec wieksza szansa byla ze mi go da	13
15	7	2023-11-30 11:23:32.625791	4	MESSAGE	Chyba ze z wami mial by duzo wspolnego	14
16	7	2023-11-30 11:24:02.005695	4	MESSAGE	Jak bedzie wiencej osob to to matchowanie jest bardziej sensoene	15
17	7	2023-11-30 11:24:19.208443	1	MESSAGE	kurde 	16
18	7	2023-11-30 11:25:01.727072	4	MESSAGE	W sensie tez nie chcemy sytucji w ktorej jedna osoba ktora ma jakies dziwne zainteresowania ktorych nikt nie ma	17
19	7	2023-11-30 11:25:06.865495	4	MESSAGE	Bedzie wiecznie sama	18
20	7	2023-11-30 11:25:12.825027	4	MESSAGE	I nikogo jej nie dobierze	19
21	7	2023-11-30 11:25:14.793537	1	MESSAGE	dobra w pompie	20
22	7	2023-11-30 11:25:19.720069	1	MESSAGE	jest git	21
23	7	2023-11-30 11:25:24.796114	4	MESSAGE	Filip nie da sie tego idealnie zrobic	22
24	7	2023-11-30 11:25:30.662048	1	MESSAGE	bedzie milionerami	23
25	7	2023-11-30 11:25:30.697273	4	MESSAGE	Nie ma rozwiazan idealnych	24
26	7	2023-11-30 11:25:46.397409	4	MESSAGE	Twoja stara jak juz	25
27	7	2023-11-30 11:27:50.825362	4	MESSAGE	A i sprawdzaj maila tego od converetti co jakis czas	26
28	7	2023-11-30 11:28:03.047035	4	MESSAGE	Bo moze sie trafic ze ktos z jakimis problemami napisze	27
29	7	2023-11-30 11:28:09.144743	4	MESSAGE	To wtedy mu ogarniemy	28
30	7	2023-11-30 11:28:19.994841	1	MESSAGE	czekaj tez ci dam haslo	29
31	7	2023-11-30 11:45:20.012618	4	MESSAGE	Tu czasem nie wysyalej	30
32	7	2023-11-30 12:01:05.218242	1	MESSAGE	na fb wyslalem	31
33	100	2023-12-04 07:48:43.109409	1	MESSAGE	Welcome everyone to the Budapest Climate Summit! You can use this chat to discuss the panel discussions and presentations taking place live on stage! 	0
34	24	2023-12-04 08:10:01.306618	1	MESSAGE	Dear Mr Mammadov - nice to meet you! I am a Journalist for CEENERGYNEWS. I often cover EU-Azerbaijan energy ties, so it would be great to chat later :) 	0
35	27	2023-12-04 10:25:42.629399	1	MESSAGE	that profile picture is fire	0
36	27	2023-12-04 11:08:46.504588	18	MESSAGE	this will be my icebreaker when I text someone here 	1
37	27	2023-12-04 11:09:28.511795	18	MESSAGE	btw would like to change my interests on my profile but can’t 	2
38	27	2023-12-04 11:09:43.501608	18	MESSAGE	shall I email them or maybe you can help? 	3
39	30	2023-12-04 11:30:56.188105	18	MESSAGE	Dear Mr. Mammadov - Hope this message finds you well. I’m Dominik Istrate from Aretera, an international public affairs firm operating across CEE, SEE, the South Caucasus and Central Asia. I’m our consultancy’s lead for CEE and the South Caucasus. I’d be very much happy to	0
40	30	2023-12-04 11:32:02.870334	18	MESSAGE	*I’d be very much happy to give an introduction and to discuss our potentially similar professional	1
41	30	2023-12-04 11:32:22.180181	18	MESSAGE	*professional interest. 	2
42	27	2023-12-04 11:42:56.640217	1	MESSAGE	annoyingly you can't change once you set it up	4
43	27	2023-12-04 11:43:18.94541	1	MESSAGE	this will be added by april	5
44	27	2023-12-04 11:45:04.263794	18	MESSAGE	no worries	6
45	29	2023-12-04 11:47:20.515291	18	MESSAGE	Dear Ekomobong, Hope this msg finds you well. I’m Dominik Istrate from Aretera, an international public affairs consultancy. We specialize in supporting businesses in a number of energy industries to operate on Central and Eastern European markets with policy analysis and government relations services. Should this be of interest, I’d be happy to give an introdution and also to learn more about your association later during the conference.	0
46	33	2023-12-04 14:36:29.349332	18	MESSAGE	Kedves Ambrus, Üdvözlöm, Istrate Dominik vagyok, az Aretera Public Affairs közép-kelet-európai piacokért felelős vezető tanácsadója. Szakpolitikai tanácsadással és vállalati érdekérvényesítéssel foglalkozunk több ágazatban, egyik központi témánk a zöld átállás. Amennyiben érdekes lehet az Ön számára, szívesen beszélnék Önnel a regionális aktualitásokról a konferencia végén a networking party-n. Üdvözlettel, Dominik	0
47	7	2023-12-05 19:07:20.996142	4	MESSAGE	Fhhh	32
48	7	2023-12-05 19:07:31.170306	4	MESSAGE	Tygthgtg	33
\.


--
-- Data for Name: panel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.panel (id, name, description, round_id, start_date, stop_date, start_notification_sent, stop_notification_sent) FROM stdin;
1	Arrival and registration		1	2023-12-04 07:30:00	2023-12-30 08:00:00	t	f
2	Welcome by the host of the Budapest Climate Summit		1	2023-12-04 08:00:00	2023-12-30 08:05:00	t	f
3	Welcome speech	Attila Steiner, State Secretary, Ministry of Energy of Hungary	1	2023-12-04 08:05:00	2023-12-30 08:15:00	t	f
4	Keynote address	Diana Ürge-Vorsatz, Vice Chair, Intergovernmental Panel on Climate Change (IPCC)	1	2023-12-04 08:15:00	2023-12-30 08:30:00	t	f
5	Platina sponsor’s welcome	Matt Simister, Central European CEO, TESCO	1	2023-12-04 08:30:00	2023-12-30 08:45:00	t	f
6	Main sponsor’s welcome	András Puskás, Deputy CEO, MBH Bank	1	2023-12-04 08:45:00	2023-12-30 09:00:00	t	f
7	Keynote address	Dr. István Nagy, Minister of Agriculture of Hungary	1	2023-12-04 09:00:00	2023-12-30 09:05:00	t	f
8	Networking Coffee		1	2023-12-04 09:05:00	2023-12-30 09:45:00	t	f
9	Keynote address	Antonella Sopranzetti, Director, Government Relations and Advocacy Europe, Low Carbon Solutions/Upstream, ExxonMobil	1	2023-12-04 09:45:00	2023-12-30 10:00:00	t	f
10	PANEL DISCUSSION	Christian Zinglersen, Director, EU ACER Zsolt Jamniczky, Deputy CEO, E.ON Hungaria László Fazekas, Deputy CEO, Chief Financial Officer, MVM Franck Neel, Member of the Executive Board, OMV Petrom Zsófia Beck, Managing Director and Partner, BCG Pál Ságvári, Vice President of the Hungarian Energy and Public Utility Regulatory Authority (Moderator)	1	2023-12-04 10:00:00	2023-12-30 10:50:00	t	f
11	PANEL DISCUSSION	"Andrea Beatrix Kádár, President, Hungarian Atomic Energy Authority Roman Romanowski, Vice President, Westinghouse Electric Company Energy Systems Alexis Honner, Business Development Manager, Rolls-Royce SMR Dóra Zombori, Partner, Dentons Dr. Csaba Kiss, Deputy CEO, Chief Generation Officer and Chief Nuclear Officer, MVM Attila Aszódi, Full Professor, Institute of Nuclear Techniques, Budapest University of Technology and Economics (Moderator)	1	2023-12-04 10:50:00	2023-12-30 11:20:00	t	f
12	Keynote address	Dr. Mátyás Vajta, CEO, HUPX	1	2023-12-04 11:20:00	2023-12-30 11:30:00	t	f
13	Fire-side chat	Dr. Mátyás Vajta, CEO, HUPX Milos Mladenovic, Managing Director, SEEPEX Claudia Patricolo, Editor-in-Chief, CEENERGYNEWS (Moderator)	1	2023-12-04 11:30:00	2023-12-30 11:45:00	t	f
14	Networking Lunch		1	2023-12-04 11:45:00	2023-12-30 13:00:00	t	f
15	LIVE FROM DUBAI	Barbara Botos, Ambassador at Large for Climate, Ministry of Energy, Hungary	1	2023-12-04 13:00:00	2023-12-30 13:15:00	t	f
16	Keynote address	Ruben Davis, Policy Officer, Cleantech for Europe	1	2023-12-04 13:15:00	2023-12-30 13:30:00	t	f
17	Keynote address	Trang Nguyen Thu , Head of Energy Efficiency Business Development, MET Central Europe	1	2023-12-04 13:30:00	2023-12-30 13:40:00	t	f
18	Keynote address	György Szege, Head of the ESG and Sustainability Department, MBH Bank	1	2023-12-04 13:40:00	2023-12-30 13:50:00	t	f
19	PANEL DISCUSSION	Péter Balogh, Corporate and Special Lending, Managing Director, MBH Bank; Réka Janosik, Executive Director in Quantitative Research, Head of Budapest Climate Risk Center, MSCI; Julian Toth, COO of ISFC Executive Director, Czech Sustainable Investment Forum and Sherpa for the EU Sustainable Finance Platform; Anders Risberg, Head of Corporate Lending Central and South Eastern Europe – EIB; Krisztina Kulcsárné Dr. Takács, Chief Financial Officer, SolServices; Tamás Pletser, EMEA Oil & Gas Analyst, Erste Investment (Moderator)	1	2023-12-04 13:50:00	2023-12-30 14:40:00	t	f
20	Networking Coffee		1	2023-12-04 14:40:00	2023-12-30 15:00:00	t	f
21	Keynote address	Dr. Gábor Farkas, Managing Director, Chief of Legal and Regulatory Affairs, SolServices	1	2023-12-04 15:00:00	2023-12-30 15:15:00	t	f
22	Keynote address	Bart Biebuyck, CEO, Green Energy Park	1	2023-12-04 15:15:00	2023-12-30 15:30:00	t	f
23	Keynote address	Dácil Borges, Global Director Consultancy, Xdroid	1	2023-12-04 15:30:00	2023-12-30 15:45:00	t	f
24	Fire-side chat	Veronika Erős, Vice Chair of the Managing Board, EIT Urban Mobility Virág Mészáros, CEO, Hungarian Mobility Development Agency Péter Kaderják, Managing Director, Hungarian Battery Association (Moderator)	1	2023-12-04 15:45:00	2023-12-30 16:10:00	t	f
25	Keynote address	Fanni Mátyók, children’s rights expert	1	2023-12-04 16:10:00	2023-12-30 16:20:00	t	f
26	Summary	Dr. Csaba Novák, President, Hungarian Renewable Energy Association	1	2023-12-04 16:20:00	2023-12-30 16:30:00	t	f
27	TOP CEE ENERGY INFLUENCERS AWARDS	By CEENERGYNEWS	1	2023-12-04 16:30:00	2023-12-30 22:59:00	t	f
\.


--
-- Data for Name: possible_answer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.possible_answer (id, caption, question_id, "order") FROM stdin;
1	Very good	1	\N
2	Good	1	\N
3	Neutral	1	\N
4	Not good	1	\N
5	Very bad	1	\N
6	Panel Discussion: EV recycling challenges in the EU	2	\N
7	Keynote Speech: Outlook on the global geothermal industry	2	\N
8	Keynote Speech: European Green Deal and its opportunities for CEE	3	\N
9	Panel Discussion: Poland - a regional leader or lagger in offshore wind energy?	3	\N
10	enter text...	4	\N
\.


--
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question (id, question, question_type, survey_id, "order") FROM stdin;
1	How are you enjoying the conference so far?	SELECT	1	\N
2	Which event are you looking forward to the most?	ONE_CHOICE_RADIOBUTTON	1	\N
3	Which event are you looking forward to the least?	ONE_CHOICE_RADIOBUTTON	1	\N
4	Anything that could be better?	TEXT_AREA	1	\N
\.


--
-- Data for Name: round; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.round (id, name, conference_id, img_path) FROM stdin;
1	Morning round	1	waiting-picture.png
2	Afternoon round	1	home-picture.png
3	Evening round	1	home-picture.png
\.


--
-- Data for Name: session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session (id, app_user_id, session_key, expiration_date) FROM stdin;
2	2	3e1e5664-7582-4b64-a7cb-8de6e33c22ea	\N
4	3	04b113ce-a085-4932-9502-6cbf206e0b00	\N
8	7	5f1cfd46-6f06-4f45-879a-7dee4672c63c	\N
9	8	be2d3dc8-df39-47fc-8c66-987d0ab138c9	\N
10	9	2fef7602-e745-459b-b2b3-aa236ae3a582	\N
11	10	d39d789f-1f55-4436-8396-cdf201e56e57	\N
12	11	479120a5-7406-4936-8dcc-9e973bc668af	\N
13	12	3f59bcf4-bf07-43ee-beca-d4e4c651f7a3	\N
15	13	de3e4e2d-7611-488d-b00f-59af6adbe433	\N
16	14	e11026c5-f613-4e36-bc15-e21dd683c506	\N
7	6	1457b2af-5729-469f-bc92-18c376999031	\N
17	15	e9608c4c-fa9c-4a7c-9074-54d1166f7705	\N
18	16	51d32d02-28e2-4930-b4eb-6d51315c4ac4	\N
19	17	4d8a0138-b7cd-449a-bbd7-195cb07db9cf	\N
21	19	ac21b94d-089f-44ad-9f47-4c526521e327	\N
22	18	62ea0c09-d9a1-4878-9d1b-26e3007ed5f2	\N
23	4	70597ea3-7907-45ae-91b1-ca3575496d60	\N
14	1	06e9c243-4516-453d-8e46-2828299c8496	\N
\.


--
-- Data for Name: survey; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.survey (id, name, round_id, start_date, stop_date, start_notification_sent, stop_notification_sent) FROM stdin;
1	Afternoon Round	1	\N	\N	f	f
\.


--
-- Name: answer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.answer_id_seq', 1, false);


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_user_id_seq', 19, true);


--
-- Name: chat_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_room_id_seq', 33, true);


--
-- Name: conference_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.conference_id_seq', 1, false);


--
-- Name: dictionary_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dictionary_id_seq', 1, false);


--
-- Name: dictionary_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dictionary_seq', 41, true);


--
-- Name: email_scheduler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.email_scheduler_id_seq', 29, true);


--
-- Name: message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.message_id_seq', 48, true);


--
-- Name: panel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.panel_id_seq', 1, false);


--
-- Name: possible_answer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.possible_answer_id_seq', 1, false);


--
-- Name: question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_id_seq', 1, false);


--
-- Name: round_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.round_id_seq', 1, false);


--
-- Name: session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_id_seq', 23, true);


--
-- Name: survey_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.survey_id_seq', 1, false);


--
-- Name: answer answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_reset_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_reset_code_key UNIQUE (reset_code);


--
-- Name: chat_room_member chat_room_member_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT chat_room_member_pkey PRIMARY KEY (chat_room_id, app_user_id);


--
-- Name: chat_room chat_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT chat_room_pkey PRIMARY KEY (id);


--
-- Name: conference conference_pin_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conference
    ADD CONSTRAINT conference_pin_key UNIQUE (pin);


--
-- Name: conference conference_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conference
    ADD CONSTRAINT conference_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: dictionary dictionary_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictionary
    ADD CONSTRAINT dictionary_pkey PRIMARY KEY (id);


--
-- Name: email_scheduler email_scheduler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_scheduler
    ADD CONSTRAINT email_scheduler_pkey PRIMARY KEY (id);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- Name: panel panel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panel
    ADD CONSTRAINT panel_pkey PRIMARY KEY (id);


--
-- Name: possible_answer possible_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.possible_answer
    ADD CONSTRAINT possible_answer_pkey PRIMARY KEY (id);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- Name: round round_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT round_pkey PRIMARY KEY (id);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- Name: survey survey_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT survey_pkey PRIMARY KEY (id);


--
-- Name: session unique_app_user_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT unique_app_user_id UNIQUE (app_user_id);


--
-- Name: chat_room_member unique_chat_room_app_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT unique_chat_room_app_user UNIQUE (chat_room_id, app_user_id);


--
-- Name: idx_chat_room_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_room_id ON public.message USING btree (chat_room_id);


--
-- Name: idx_order_in_chat; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_in_chat ON public.message USING btree (order_in_chat);


--
-- Name: answer fk_answer_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk_answer_app_user FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- Name: answer fk_answer_possible_answer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk_answer_possible_answer FOREIGN KEY (possible_answer_id) REFERENCES public.possible_answer(id);


--
-- Name: chat_room fk_chat_room_conference; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT fk_chat_room_conference FOREIGN KEY (conference_id) REFERENCES public.conference(id);


--
-- Name: chat_room_member fk_chat_room_member_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT fk_chat_room_member_app_user FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- Name: chat_room_member fk_chat_room_member_chat_room; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT fk_chat_room_member_chat_room FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(id);


--
-- Name: chat_room_member fk_chat_room_member_message; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT fk_chat_room_member_message FOREIGN KEY (last_read_message_id) REFERENCES public.message(id);


--
-- Name: chat_room fk_chat_room_panel; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT fk_chat_room_panel FOREIGN KEY (panel_id) REFERENCES public.panel(id);


--
-- Name: chat_room fk_chat_room_round; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT fk_chat_room_round FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: app_user fk_conference_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fk_conference_app_user FOREIGN KEY (selected_conference_id) REFERENCES public.conference(id);


--
-- Name: app_user fk_dict_interest_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fk_dict_interest_app_user FOREIGN KEY (dict_interest_id) REFERENCES public.dictionary(id);


--
-- Name: app_user fk_dict_occupation_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fk_dict_occupation_app_user FOREIGN KEY (dict_occupation_id) REFERENCES public.dictionary(id);


--
-- Name: message fk_message_chat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk_message_chat FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(id);


--
-- Name: message fk_message_sender; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk_message_sender FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- Name: panel fk_panel_round; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panel
    ADD CONSTRAINT fk_panel_round FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: possible_answer fk_possible_answer_question; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.possible_answer
    ADD CONSTRAINT fk_possible_answer_question FOREIGN KEY (question_id) REFERENCES public.question(id);


--
-- Name: question fk_question_survey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk_question_survey FOREIGN KEY (survey_id) REFERENCES public.survey(id);


--
-- Name: round fk_round_conference; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT fk_round_conference FOREIGN KEY (conference_id) REFERENCES public.conference(id);


--
-- Name: session fk_session_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fk_session_app_user FOREIGN KEY (app_user_id) REFERENCES public.app_user(id);


--
-- Name: survey fk_survey_round; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT fk_survey_round FOREIGN KEY (round_id) REFERENCES public.round(id);


--
-- Name: app_user fk_target_occupation_app_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fk_target_occupation_app_user FOREIGN KEY (dict_target_occupation_id) REFERENCES public.dictionary(id);


--
-- PostgreSQL database dump complete
--

